version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/hospital_management?sslmode=disable
      - JWT_SECRET=asdj8123kdsavcilkdsamm129majksdIAnjdsaSM124
      - PORT=8080
      - ENV=development
    depends_on:
      - db
    volumes:
      - ./web:/root/web
    networks:
      - hospital_network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital_management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/infrastructure/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - hospital_network

volumes:
  db_data:

networks:
  hospital_network:
    driver: bridge